image: golang:1.19

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - test

test:
  extends: .go-cache
  stage: test
  services:
    - name: cockroachdb/cockroach:latest
      alias: db
      command: ["start-single-node", "--insecure"]
  tags:
    - gitlab-runner
  script:
    - go test ./...